name: Notify Slack for Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.title, 'word')"
    steps:
      - name: Notify Slack
        uses: slack/webhook@v1
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: 'A new pull request containing the word "word" has been opened!'

