# This is a basic workflow to help you get started with Actions

name: Notify Slack for Pull Request

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
       id-token: write
       contents: read # default
    if: "contains(github.event.pull_request.title, 'word')"
    steps:
      - name: Notify Slack
        uses: slack/webhook@v1
        env:
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: '#alerta'
          username: 'GitHub Actions'
          icon_emoji: ':rocket:'
          text: 'A new pull request containing the word "word" has been opened!'
