# This is a basic workflow to help you get started with Actions

name: Notify Slack for Pull Request

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.title, 'word')"
    steps:
      - name: Notify Slack
      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_channel: alerta
          slack_username: Github
          text: 'A new pull request containing the word "word" has been opened!'
